---
development:
  dialect: postgres
  database: microsocial_development
  user: buffalo
  password: buffalo
  host: localhost
  pool: 5

test:
    url: {{envOr "TEST_DATABASE_URL" "postgres://buffalo:buffalo@localhost:5432/microsocial_test?sslmode=disable"}}

production:
    url: {{envOr "DATABASE_URL" "postgres://buffalo:buffalo@db:5432/microsocial?sslmode=disable"}}
