---
development:
  dialect: postgres
  database: microsocial_development
  user: buffalo
  password: buffalo
  host: 127.0.0.1
  pool: 5

test:
    url: {{envOr "TEST_DATABASE_URL" "postgres://buffalo:buffalo@127.0.0.1:5432/microsocial_test?sslmode=disable"}}

production:
    url: {{envOr "DATABASE_URL" "postgres://buffalo:buffalo@127.0.0.1:5432/microsocial_production?sslmode=disable"}}
